workflow:
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        DOCKER_IMAGE_NAME: '$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG'
    - if: $CI_COMMIT_BRANCH
      variables:
        DOCKER_IMAGE_NAME: '$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH'
        MODEL: '$CI_COMMIT_BRANCH'

variables:
  GITLAB_RUNNER_TAG: 'default-runner'
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  MODEL: 'production'

stages:
  - images

build:
  stage: images
  image: docker:cli
  tags:
    - ${GITLAB_RUNNER_TAG}
  services:
    - docker:dind
  rules:
    - if: $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
      exists:
        - Dockerfile
    - when: never
  before_script:
    - |
      if [[ "$MODEL" != "dev" && "$MODEL" != "test" && "$MODEL" != "production" ]]; then
        echo "MODEL=$MODEL 不合法，自动设为 dev"
        export MODEL="dev"
      fi
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull --build-arg MODEL="${MODEL}" -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"